language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "rfO1uR7M6MDoECvDL1UTwwu0LlJPc6iA1MBtzkpOCMuCtx4NvYnbDtJYpgjjk6BQRy2nwDQz3QlqCj3aH0EuyRFXuUcc4NMGlwJAJ2SUPhIOJkRQwd3BGrATSPjNRRfn+ZnHf9P3JYO/5rLmkejvWvdoFuoicA0giJ1pqbHX2Me7MbFvButm0FVHDKipxZM03BzOAk3EaOfJwi2E+PzKxydhYSyMzVWO0czyXEOCDmidEGjEmLuIWuOeXfbJBbdNw/noEitwP3kUOZtdsgik8zU2v43fpb6yr6Q1aYZ6CoRoSY9j5VeS7p1Y6PPjw1ENd0a5i+g2Y4mxo+VoTjj2U9ivdI3YZO9m5Kpdhi5riHg7fid46uzzpFoqiRHnBjo3MHNMAHBxcgkrO5+Jc4sfQcOlvM/QVzEN6GmIPSvtsDxi6IAffNTdfUH8a7tD4zJQ5/6txxzAIoE3zsWxQP+l1/SpjlIuhHQqeaPOSWDQewFoux1oBBNH8xDincWlHjZDGwH8+/EDCMHK0DrDMI3F1SxullNXjfCVUr6ZOQE/NSCP3bwhKwO1RwhneyHEP2XbtlMd3ktgODZcYiyrZrQX+BcFdi2g/1ZMV/BmyY1K5jRcZmbBvNg2iDeWy2J/pGmGvr17eUkJFg+/AstlttyxQE/d9iF4QF2syfP8hLD0MeI="
    - secure: "S7Iu/lIwIfwfjdamrPKmQWYbYtRljbVmK+CYWg346SHMaQX4Z2Wr6GTQ4gUOtYnrJjmkAJU7U2FQcUKHCKdBYr1ZlkbYE6K6P+gDb5X/7Fv7k2c3iHHBm3x4GjZq2ZKFMx+NxWIcWWPM4oYP2LRbFyR32470MCU8Px6rhD4+Da0bz40OWvrwNu2hmjO7Frs0pzHFaIHr7oDK8ICtqluuj+FGLn4FQLvBe6gNMSIwvZk4hjAfNli6Arn+Q0UPYcpYTSCxBGQgcAuyn+rMIASmBfI02C1JmP+Jb8YQHQQyegPor3WOXyaiG3lFR6j8WJws4jKQB7TnbrTgMDrNAhbISjjqBkrtyui0vzvVbF0lXc6Cdo47HD70/9rjMYnL7WWUwtkQZKLLTnNQQJpeJ9DmGpqPgYlczEY1LQBXoj4dgrH8a3q89+1VWzADLrjS0Q7/HGm3NPCeMjZVFzPxrXY3UZYP4PStyQmrPOWlpOb1KAE0eXHKzbr4JOxojS0rzZv5sG0c6F30+8Wh2eOhf/twMfo8MVtyTBvP2eWHQH8EO+/rikFKZNNIxHJEfPrg7xhktLDJhHVZlY/RuXK5BpoC2cUwrPF4NciIQx5FmljXQRGwo47Z6wf2jNywSgDidX73WQeWY1W8490/Ke7LgQqAVEMrSX0l1uckkfMlpXQ4A0E="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
